name: Test

on:
  workflow_call:
    inputs:
      php:
        default: '8.4'
        type: string
      mysql:
        default: '8.4'
        type: string
      node:
        default: '22'
        type: string

env:
  CACHE_STORE: array
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: ''

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:${{ inputs.mysql }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: ${{ env.DB_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, :php-psr
          coverage: none

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}

      - name: Copy environment file
        run: cp .env.example .env

      - name: Install Composer dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --no-interaction --no-progress --no-scripts

      - name: Install npm dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --compact

permissions:
  contents: read
  packages: read
